AWSTemplateFormatVersion: 2010-09-09
Resources:
  DevEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-053284fc22a2c3f82
      InstanceType: t2.micro
      KeyName: Windows-Mumbai-Keypair-2024